### ISSUE TITLE
Allowed tactics in Level 5 in the Redux Or World

### ISSUE THREAD

**Issue by debbie-drg** [Trequetrum/lean4game-logic#2]
I believe you intended to allow the tactic cases in [this level](https://github.com/Trequetrum/lean4game-logic/blob/main/Game/Levels/OrTactic/L05.lean). It is used in the intended solution and I otherwise don't see an obvious way to solve it with the current allowed tactics.

**Comment by Trequetrum** [comment]
Yes, you're absolutely right!

**Comment by Trequetrum** [comment]
Fixed :)
